### ISSUE TITLE
 Error processing checkout. Please try again

### ISSUE THREAD

**Issue by cyberninja13** [Tap-Payments/Plugin-WooCommerce#9]
I got error when anyone trying to Place Orders

" Error processing checkout. Please try again"

The payment gateway data has been verified and is all keys correct, but it seems that something is missing or needs to be updated

any way the error i got now stopping the Clint's from payment

also i check the logs files and see the error 

2023-11-07T02:24:09+00:00 CRITICAL Cannot redeclare tap_add_gateway_class() (previously declared in /home/u857197653/domains/hiresme.ai/public_html/wp-content/plugins/Plugin-WooCommerce-CC-beta/tap.php:43) in /home/u857197653/domains/hiresme.ai/public_html/wp-content/plugins/Plugin-WooCommerce-All-in-one-master/tap.php on line 16

Based on that log, there is an issue from the PHP file from your plugin and i need the developer to solve the issue if possible as i one of Tap clients 

![1)](https://github.com/Tap-Payments/Plugin-WooCommerce-All-in-one/assets/120660656/9f476385-d556-4fce-832e-ca0a5597f608)

**Comment by rjakhartap** [comment]
At a time you should have only one plugin enabled, Try removing the other tap plugin installed.

_Plugin-WooCommerce-All-in-one-master_ already have all the features. 

Please remove/delete _Plugin-WooCommerce-CC-beta_
